<?php


class MoveablePoint extends Point
{
    public $xSpeed, $ySpeed;

    public function __construct($x, $y, $xSpeed, $ySpeed)
    {
        parent::__construct($x, $y);
        $this->xSpeed = floatval($xSpeed);
        $this->ySpeed = floatval($ySpeed);
    }


    public function getXSpeed()
    {
        return $this->xSpeed;
    }


    public function getYSpeed()
    {
        return $this->ySpeed;
    }


    public function setXSpeed($xSpeed)
    {
        $this->xSpeed = $xSpeed;
    }

    public function setYSpeed($ySpeed)
    {
        $this->ySpeed = $ySpeed;
    }

    public function setXySpeed($xSpeed, $ySpeed)
    {
        $this->xSpeed = $xSpeed;
        $this->ySpeed = $ySpeed;
    }

    public function getXySpeed()
    {
        return $arr = [$this->xSpeed, $this->ySpeed];
    }

    public function toString()
    {
        parent::toString(); // TODO: Change the autogenerated stub
        echo ' = ' . $this->xSpeed . ' , ' . $this->ySpeed;
    }

    public function move()
    {
        $this->x += $this->xSpeed;
        $this->y += $this->ySpeed;
        return this;
    }
}